---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: talltale
  labels:
    app: talltale
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: talltale
  template:
    metadata:
      labels:
        app: talltale
    spec:
      containers:
        - name: talltale
          image: localhost:32000/talltale:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_PATH
              value: /app/database.db

            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: talltale-secret
                  key: SECRET_KEY_BASE

            - name: PHX_HOST
              value: talltale.ulfurinn.net

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: talltale
  labels:
    app: talltale
spec:
  ports:
    - port: 80
      targetPort: 4000
  selector:
    app: talltale
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: talltale
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  tls:
    - hosts:
        - talltale.ulfurinn.net
      secretName: talltale-ingress-tls
  rules:
    - host: talltale.ulfurinn.net
      http:
        paths:
          - backend:
              service:
                name: talltale
                port:
                  number: 80
            path: /
            pathType: Prefix
